sonar.projectKey=SamuelDonovan_minimost
sonar.organization=samueldonovan
sonar.projectName=MiniMost

sonar.sources=src/minimost
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.python.coverage.reportPaths=coverage.xml
