name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - run: pip install build black bandit semgrep
      - run: black --check src/
      - run: bandit -r src/
      - run: semgrep scan --config=p/python --config=p/flask src/
      - run: python -m build --wheel
      - uses: actions/upload-artifact@v6
        with:
          name: minimost-wheel
          path: dist/*.whl
